global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'sockperf'
    static_configs:
      - targets: ['instance-1:9091', 'instance-2:9091']
        labels:
          group: 'sockperf'
          environment: 'test'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'monitoring'
