{
 "title": "sockperf Performance Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TCP Latency Comparison - Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"tcp\"}",
     "legendFormat": "{{interface}} - Avg Latency"
    }
   ]
  },
  {
   "title": "TCP Latency Comparison - p99.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"tcp\"}",
     "legendFormat": "{{interface}} - p99.9 Latency"
    }
   ]
  },
  {
   "title": "UDP Latency Comparison - Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"udp\"}",
     "legendFormat": "{{interface}} - Avg Latency"
    }
   ]
  },
  {
   "title": "UDP Latency Comparison - p99.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"udp\"}",
     "legendFormat": "{{interface}} - p99.9 Latency"
    }
   ]
  },
  {
   "title": "TCP Throughput Comparison",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sockperf_throughput_mbps{test_type=\"throughput\",protocol=\"tcp\"}",
     "legendFormat": "{{interface}} - Throughput"
    }
   ]
  },
  {
   "title": "UDP Throughput Comparison",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sockperf_throughput_mbps{test_type=\"throughput\",protocol=\"udp\"}",
     "legendFormat": "{{interface}} - Throughput"
    }
   ]
  },
  {
   "title": "ENA Express Improvement Percentage",
   "type": "graph",
   "description": "Improvement percentage calculated as ((ENA - ENA Express) / ENA) * 100",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena\"} - sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena_express\"}) / sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena\"}",
     "legendFormat": "TCP Avg Latency Improvement %"
    },
    {
     "expr": "100 * (sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena\"} - sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena_express\"}) / sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"tcp\",interface=\"ena\"}",
     "legendFormat": "TCP p99.9 Latency Improvement %"
    },
    {
     "expr": "100 * (sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena\"} - sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena_express\"}) / sockperf_latency_avg_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena\"}",
     "legendFormat": "UDP Avg Latency Improvement %"
    },
    {
     "expr": "100 * (sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena\"} - sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena_express\"}) / sockperf_latency_p999_usec{test_type=\"ping-pong\",protocol=\"udp\",interface=\"ena\"}",
     "legendFormat": "UDP p99.9 Latency Improvement %"
    }
   ]
  }
 ]
}